apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cosmosdb-diagnostic-exporter
  labels:
    app: cosmosdb-diagnostic-exporter
spec:
  serviceName: cosmosdb-diagnostic-exporter
  replicas: 1
  selector:
    matchLabels:
      app: cosmosdb-diagnostic-exporter
  template:
    metadata:
      labels:
        app: cosmosdb-diagnostic-exporter
    spec:
      containers:
        - name: exporter
          image: us-docker.pkg.dev/grafanalabs-dev/docker-prometheus-cosmosdb-diagnostic-exporter-dev/prometheus-cosmosdb-diagnostic-exporter:latest
          args:
            - /etc/exporter/config.yaml
          env:
            - name: OTLP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-diagnostic-exporter
                  key: otlp-username
                  optional: true
            - name: OTLP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cosmosdb-diagnostic-exporter
                  key: otlp-password
                  optional: true
          volumeMounts:
            - name: config
              mountPath: /etc/exporter
              readOnly: true
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: cosmosdb-diagnostic-exporter
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Mi
